name: Deploy Django Backend to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build SAM Application
        run: sam build

      - name: Deploy SAM Application
        run: >
          sam deploy 
          --stack-name my-django-stack-staging
          --resolve-s3
          --resolve-image-repos
          --capabilities CAPABILITY_IAM
          --no-confirm-changeset 
          --no-fail-on-empty-changeset
          --parameter-overrides
          VpcSecurityGroupId=${{ secrets.VPC_SECURITY_GROUP_ID }}
          VpcSubnetId=${{ secrets.VPC_SUBNET_ID }}
          Stage=staging

      - name: Staging Health Check
        run: >
          curl --fail --silent --show-error ${{ secrets.API_GATEWAY_STAGING }}/api/health/ -w "\nHTTP Status: %{http_code}\n" -o /dev/null


  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install the AWS SAM CLI
      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      # 4. Log in to your AWS account using the secrets you saved
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # 5. Build your Docker container (exactly like running it on your laptop)
      - name: Build SAM Application
        run: sam build

      # 6. Deploy to AWS! 
      # The flags tell SAM not to wait for you to press "Y" to confirm
      - name: Deploy SAM Application
        run: >
          sam deploy 
          --stack-name my-django-stack
          --resolve-s3
          --resolve-image-repos
          --capabilities CAPABILITY_IAM
          --no-confirm-changeset 
          --no-fail-on-empty-changeset
          --parameter-overrides
          VpcSecurityGroupId=${{ secrets.VPC_SECURITY_GROUP_ID }}
          VpcSubnetId=${{ secrets.VPC_SUBNET_ID }}
          Stage=prod

      - name: Prod Health Check
        run: >
          curl --fail --silent --show-error ${{ secrets.API_GATEWAY }}/api/health/ -w "\nHTTP Status: %{http_code}\n" -o /dev/null